packages:
  url-shortener/internal/http-server/handlers/url/save:
    interfaces:
      URLSaver:
        config:
          dir: "{{.InterfaceDir}}/mocks"
          filename: "mock_url_saver.go"
          pkgname: "mocks"
          structname: "MockURLSaver"
  url-shortener/internal/http-server/handlers/redirect:
    interfaces:
      URLGetter:
        config:
          dir: "{{.InterfaceDir}}/mocks"
          filename: "mock_url_getter.go"
          pkgname: "mocks"
          structname: "MockURLGetter"
  url-shortener/internal/http-server/handlers/url/delete:
    interfaces:
      URLDeleter:
        config:
          dir: "{{.InterfaceDir}}/mocks"
          filename: "mock_url_deleter.go"
          pkgname: "mocks"
          structname: "MockURLDeleter"
